import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getFooterRes, getNavRes } from "@/helper";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navRes = await getNavRes();
  const footerRes = await getFooterRes();
  if (!navRes) throw new Error("Status code 404");
  return (
    <html lang="en">
      <body className={inter.className}>
        {navRes && <Navbar navRes={navRes} />}
        {children}
        {navRes && <Footer footerRes={footerRes} />}
      </body>
    </html>
  );
}
